package com.noah.manage.dao.domain;

public class MUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_users.user_id
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_users.user_name
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_users.pass_word
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    private String passWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_users.is_delete
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_users.user_id
     *
     * @return the value of m_users.user_id
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_users.user_id
     *
     * @param userId the value for m_users.user_id
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_users.user_name
     *
     * @return the value of m_users.user_name
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_users.user_name
     *
     * @param userName the value for m_users.user_name
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_users.pass_word
     *
     * @return the value of m_users.pass_word
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_users.pass_word
     *
     * @param passWord the value for m_users.pass_word
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_users.is_delete
     *
     * @return the value of m_users.is_delete
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_users.is_delete
     *
     * @param isDelete the value for m_users.is_delete
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}