package com.noah.manage.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.noah.manage.dao.domain.MUsers;
import com.noah.manage.dao.domain.MUsersExample;

public interface MUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_users
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    int countByExample(MUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_users
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    int deleteByExample(MUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_users
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_users
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    int insert(MUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_users
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    int insertSelective(MUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_users
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    List<MUsers> selectByExample(MUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_users
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    MUsers selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_users
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    int updateByExampleSelective(@Param("record") MUsers record, @Param("example") MUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_users
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    int updateByExample(@Param("record") MUsers record, @Param("example") MUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_users
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    int updateByPrimaryKeySelective(MUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_users
     *
     * @mbggenerated Fri Dec 11 11:29:10 CST 2015
     */
    int updateByPrimaryKey(MUsers record);
    
    /**
     * 根据id查找可访问的URL
     * @param userId
     * @return
     */
    List<String> getAuthUrlListByUserId(String id);
    
}